CREATE TABLE bank_account
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name                     VARCHAR(255),
    last_name                      VARCHAR(255),
    overdraft_amount_authorization DECIMAL,
    account_type                   VARCHAR(255),
    CONSTRAINT pk_bank_account PRIMARY KEY (id)
);
CREATE TABLE account_transaction
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_type VARCHAR(255),
    amount           DECIMAL,
    transaction_date TIMESTAMP,
    account_id       BIGINT,
    CONSTRAINT pk_account_transaction PRIMARY KEY (id)
);